version: 2

models:
  - name: msoa_ethnicity_accommodation
    description: "Reading in data from ONS"
    config:
        materialized: external
        location: 's3://bkt.standard/ons_census2021/msoa_ethnicity_accommodation/data'
        format: parquet
        glue_register: true
        glue_database: ons_census2021