version: 2
sources:

  - name: geo
    description: "All source files in s3://bkt.raw/geo/"
    tables:
      - name: dim_country
      - name: dim_region
      - name: dim_lad
      - name: dim_cua
      - name: dim_post_town
      - name: dim_msoa
      - name: dim_lsoa
      - name: dim_post_code
      - name: area_types
      - name: post_town_geo_mapping

      - name: Local_Authority_Districts_May_2024_Boundaries_UK_BFC_-6788913184658251542.geojson
        config:
          external_location: st_read(
            'local_files/Local_Authority_Districts_May_2024_Boundaries_UK_BFC_-6788913184658251542.geojson'
            )

      - name: Lower_layer_Super_Output_Areas_2021_EW_BFC_V8_-8407643096148449625.geojson
        config:
          external_location: st_read(
            'local_files/Lower_layer_Super_Output_Areas_2021_EW_BFC_V8_-8407643096148449625.geojson'
            )

      - name: MOSA_2021_EW_BFC_V6_8073017919673588333.geojson
        config:
          external_location: st_read(
            'local_files/MOSA_2021_EW_BFC_V6_8073017919673588333.geojson'
            )

      - name: Counties_and_Unitary_Authorities_December_2024_Boundaries_UK_BFC_3348038940373313033.geojson
        config:
          external_location: st_read(
            'local_files/Counties_and_Unitary_Authorities_December_2024_Boundaries_UK_BFC_3348038940373313033.geojson'
            )

      - name: Regions_December_2024_Boundaries_EN_BFC_1195854647342073399.geojson
        config:
          external_location: st_read(
            'local_files/Regions_December_2024_Boundaries_EN_BFC_1195854647342073399.geojson'
            )

      - name: Countries_December_2024_Boundaries_UK_BFC_-7061626699629882825.geojson
        config:
          external_location: st_read(
            'local_files/Countries_December_2024_Boundaries_UK_BFC_-7061626699629882825.geojson'
            )

      - name: dim_post_town.geojson
        config:
          external_location: "st_read(
            'local_files/dim_post_town.geojson'
            )"

      - name: postcodes.csv
        description: "Downloaded from https://www.doogal.co.uk/files/postcodes.zip"
        config:
          external_location: 'local_files/postcodes.csv'


  - name: ons_housing
    tables:
      - name: hpi
      - name: pipr

      - name: UK-HPI-full-file-2025-04.csv
        description: "Downloaded from https://www.gov.uk/government/collections/uk-house-price-index-reports-2025"
        config:
          external_location: read_csv(
            'https://publicdata.landregistry.gov.uk/market-trend-data/house-price-index-data/UK-HPI-full-file-2025-07.csv'
            )

      - name: priceindexofprivaterentsukmonthlypricestatistics.xlsx
        description: "Downloaded from https://www.ons.gov.uk/economy/inflationandpriceindices/datasets/priceindexofprivaterentsukmonthlypricestatistics"
        config:
          external_location: read_xlsx(
            'https://www.ons.gov.uk/file?uri=/economy/inflationandpriceindices/datasets/priceindexofprivaterentsukmonthlypricestatistics/17september2025/priceindexofprivaterentsukmonthlypricestatistics.xlsx'
            , range = 'A3:AN'
            , sheet='Table 1'
            , stop_at_empty = true
            , all_varchar=true
            )

      - name: housingaffordabilityratiosformiddlelayersuperoutputareas140624_table3.xlsx
        description: "Downloaded from https://www.ons.gov.uk/peoplepopulationandcommunity/housing/datasets/housingaffordabilityratiosformiddlelayersuperoutputareas"
        config:
          external_location: read_xlsx(
            's3://bkt.standard/ons_housing/_affordability/raw_file/housingaffordabilityratiosformiddlelayersuperoutputareas140624.xlsx'
            , range = 'A4:I'
            , sheet='Table 3'
            , stop_at_empty = true
            , all_varchar=true
            , header=true
            )

      - name: housingaffordabilityratiosformiddlelayersuperoutputareas140624_table2.xlsx
        description: "Downloaded from https://www.ons.gov.uk/peoplepopulationandcommunity/housing/datasets/housingaffordabilityratiosformiddlelayersuperoutputareas"
        config:
          external_location: read_xlsx(
            's3://bkt.standard/ons_housing/_affordability/raw_file/housingaffordabilityratiosformiddlelayersuperoutputareas140624.xlsx'
            , range = 'A4:E'
            , sheet='Table 2'
            , stop_at_empty = true
            , all_varchar=true
            , header=true
            )

      - name: housingaffordabilityratiosformiddlelayersuperoutputareas140624_table1.xlsx
        description: "Downloaded from https://www.ons.gov.uk/peoplepopulationandcommunity/housing/datasets/housingaffordabilityratiosformiddlelayersuperoutputareas"
        config:
          external_location: read_xlsx(
            's3://bkt.standard/ons_housing/_affordability/raw_file/housingaffordabilityratiosformiddlelayersuperoutputareas140624.xlsx'
            , range = 'A4:I'
            , sheet='Table 1'
            , stop_at_empty = true
            , all_varchar=true
            , header=true
            )

  - name: ons_census2021
    tables:
      - name: imd
      - name: msoa_age
      - name: msoa_ethnicity_accommodation

      - name: TS011-2021-6-filtered-2025-06-28T09_28_22Z.csv
        description: "LSOA level data, downloaded from https://www.ons.gov.uk/datasets/TS011/editions/2021/versions/6#variables"
        config:
          external_location: read_csv(
            'https://static.ons.gov.uk/datasets/7b1bfcea-e74e-486f-9c7d-65c3f9b264f3/TS011-2021-6-filtered-2025-06-28T09:28:22Z.csv',
            delim=',',
            quote='"'
            )

      - name: TS007-2021-1-filtered-2025-06-28T09_43_09Z.csv
        description: "Age by single year downloaded from https://www.ons.gov.uk/datasets/TS007/editions/2021/versions/3#variables"
        config:
          external_location: read_csv(
            'https://static.ons.gov.uk/datasets/9252f297-0c64-4cdb-bc36-8af5be394455/TS007-2021-1-filtered-2025-06-28T09:43:09Z.csv',
            delim=',',
            quote='"'
            )

      - name: RM026-2021-1-filtered-2025-06-28T23_14_26Z.csv
        description: "MSOA level data downloaded from https://www.ons.gov.uk/datasets/RM026/editions/2021/versions/1#variables"
        config:
          external_location: read_csv(
            'https://static.ons.gov.uk/datasets/de1505bb-58df-4d3d-b105-c4ce7a3d69a1/RM026-2021-1-filtered-2025-06-28T23:14:26Z.csv',
            escape='"'
            )
