version: 2
sources:

  - name: geojsons
    tables:
      - name: Local_Authority_Districts_May_2024_Boundaries_UK_BFC_-6788913184658251542.geojson
        config:
          external_location: st_read(
            'local_files/Local_Authority_Districts_May_2024_Boundaries_UK_BFC_-6788913184658251542.geojson'
            )

      - name: Lower_layer_Super_Output_Areas_2021_EW_BFC_V8_-8407643096148449625.geojson
        config:
          external_location: st_read(
            'local_files/Lower_layer_Super_Output_Areas_2021_EW_BFC_V8_-8407643096148449625.geojson'
            )

      - name: MOSA_2021_EW_BFC_V6_8073017919673588333.geojson
        config:
          external_location: st_read(
            'local_files/MOSA_2021_EW_BFC_V6_8073017919673588333.geojson'
            )

      - name: Counties_and_Unitary_Authorities_December_2024_Boundaries_UK_BFC_3348038940373313033.geojson
        config:
          external_location: st_read(
            'local_files/Counties_and_Unitary_Authorities_December_2024_Boundaries_UK_BFC_3348038940373313033.geojson'
            )

      - name: Regions_December_2024_Boundaries_EN_BFC_1195854647342073399.geojson
        config:
          external_location: st_read(
            'local_files/Regions_December_2024_Boundaries_EN_BFC_1195854647342073399.geojson'
            )

      - name: Countries_December_2024_Boundaries_UK_BFC_-7061626699629882825.geojson
        config:
          external_location: st_read(
            'local_files/Countries_December_2024_Boundaries_UK_BFC_-7061626699629882825.geojson'
            )

      - name: dim_post_town.geojson
        config:
          external_location: "st_read(
            'local_files/dim_post_town.geojson'
            )"

  - name: doogal
    tables:
      - name: postcodes.csv
        description: "Downloaded from https://www.doogal.co.uk/files/postcodes.zip"
        config:
          external_location: "local_files/postcodes.csv"

  - name: house-price-index-data
    tables:
      - name: UK-HPI-full-file-2025-04.csv
        config:
          external_location: read_csv(
            'https://publicdata.landregistry.gov.uk/market-trend-data/house-price-index-data/UK-HPI-full-file-2025-04.csv'
            )

  - name: price-index-of-private-rents
    tables:
      - name: priceindexofprivaterentsukmonthlypricestatistics.xlsx
        config:
          external_location: read_xlsx(
            'https://www.ons.gov.uk/file?uri=/economy/inflationandpriceindices/datasets/priceindexofprivaterentsukmonthlypricestatistics/18june2025/priceindexofprivaterentsukmonthlypricestatistics.xlsx'
            , range = 'A3:AN'
            , sheet='Table 1'
            , stop_at_empty = true
            , all_varchar=true
            )

  - name: index-of-multiple-deprivation
    tables:
      - name: TS011-2021-6-filtered-2025-06-28T09_28_22Z.csv
        config:
          external_location: read_csv(
            'https://static.ons.gov.uk/datasets/7b1bfcea-e74e-486f-9c7d-65c3f9b264f3/TS011-2021-6-filtered-2025-06-28T09:28:22Z.csv',
            delim=',',
            quote='"'
            )

  - name: population
    tables:
      - name: TS007-2021-1-filtered-2025-06-28T09_43_09Z.csv
        config:
          external_location: read_csv(
            'https://static.ons.gov.uk/datasets/9252f297-0c64-4cdb-bc36-8af5be394455/TS007-2021-1-filtered-2025-06-28T09:43:09Z.csv',
            delim=',',
            quote='"'
            )

      - name: msoa-ethnicity-accommodation
        config:
          external_location: read_csv(
            'https://static.ons.gov.uk/datasets/de1505bb-58df-4d3d-b105-c4ce7a3d69a1/RM026-2021-1-filtered-2025-06-28T23:14:26Z.csv',
            escape='"'
            )


  - name: geo
    tables:
      - name: dim_country
      - name: dim_region
      - name: dim_lad
      - name: dim_cua
      - name: dim_post_town
      - name: dim_msoa
      - name: dim_lsoa
      - name: dim_post_code

  - name: ons_housing
    tables:
      - name: hpi
      - name: pipr

  - name: ons_census2021
    tables:
      - name: imd
      - name: pipr
      - name: msoa_age
      - name: msoa_ethnicity_accommodation
