version: 2

models:
  - name: affordability_ratio
    description: "Reading in data from ONS"
    config:
        materialized: table
        database: mart
        schema: ons_housing

  - name: affordability_gross_income
    description: "Reading in data from ONS"
    config:
        materialized: table
        database: mart
        schema: ons_housing

  - name: affordability_median_price
    description: "Reading in data from ONS"
    config:
        materialized: table
        database: mart
        schema: ons_housing

  - name: affordability
    description: "Joining the 3 tables above"
    config:
        materialized: table
        database: mart
        schema: ons_housing
