name: Land registry

on:
  push:
    branches: 'main'
    paths: ['backend/models/land_reg/**', '.github/workflows/land_registry.yml']

permissions:
  contents: read
  id-token: write

jobs:
  download-and-process:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/models/land_reg/land_registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: mcblair/configure-aws-profile-action@v1.0.0
        with:
            role-arn: ${{ secrets.GH_EASY_SM_ROLE }}
            profile-name: personal
            region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U easy-sm awscli --no-cache

      - name: Docker setup for the app to run on Sagemaker
        run: |
          easy_sm build -a land-registry
          easy_sm push -a land-registry

      - name: Download data
        run: |
          easy_sm cloud process -f download_land_registry.py -a land-registry -n land-registry-download -r $SAGEMAKER_EXECUTION_ROLE -e ml.m4.10xlarge
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SAGEMAKER_EXECUTION_ROLE: ${{ secrets.SAGEMAKER_EXECUTION_ROLE }}

      - name: Process data
        run: |
          easy_sm cloud process -e ml.m4.10xlarge -c 1 -r $SAGEMAKER_EXECUTION_ROLE -n lr-process -f process_data.py -a land-registry
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SAGEMAKER_EXECUTION_ROLE: ${{ secrets.SAGEMAKER_EXECUTION_ROLE }}
