version: 2

models:
  - name: post_town_geo_mapping
    description: "Because post_town is a non standard geography, parry down geos to/from post_town for consistency in membership"
    config:
        materialized: table